displayEnabled = true
x = 472
y = 450
useDefaultTotem = false
displayColors = true
coloredXpBar = false
alwaysShowBar = false
showPopCounter = false
counterEnabled = true
separator = true
counterColors = true
showInTab = false
disableArmorStands = false
